# $Id$

CFLAGS=-g -I/usr/X11R6/include -I/usr/local/include
LDFLAGS=-g -L/usr/X11R6/lib -lX11 -lXtst

all: xdotool

clean:
	rm *.o

xdo.o:
	gcc $(CFLAGS) -c xdo.c

xdotool.o:
	gcc $(CFLAGS) -c xdotool.c

xdotool: xdotool.o xdo.o
	gcc $(CFLAGS) $(LDFLAGS) xdotool.o xdo.o -o $@

package:
	NAME=xdotool-`date +%Y%m%d`; \
	mkdir $${NAME}; \
	rsync --exclude .svn -av *.c *.h README Makefile $${NAME}/; \
	tar -zcf $${NAME}.tar.gz $${NAME}/; \
	rm -rf $${NAME}/

